### ISSUE TITLE
Load docvars from directory structure

### ISSUE THREAD

**Issue by adamobeng** [kbenoit/readtext#10]
@pnulty, how do you see this working?

**Comment by pnulty** [comment]
The simplest use case is one in which the user has a directory containin subdirectories which contain texts with different docvars. For example, a user might have a "manifestos" directory, with sub-directories "Con", "Lab", and "LD" containing manifestos from different parties. The user would supply a name for the docvar (e.g. "party") when reading in the texts, and the resulting dataframe would have a "party" docvar with values for each text according to the subdirectory it was in. 

With more than one level it's more complicated, as we don't support hierarchical docvars, but getting this relatively simple case working would be good.

**Comment by kbenoit** [comment]
So hierarchical docvars from directory names could be:

`mydata <- readtext("myfiles/*", docvarnames = c("party", "type")`)

with the file structure looking like:

```
myfiles/Con/speeches/speech1.txt
myfiles/Con/speeches/speech2.txt
myfiles/Con/manifesto/man1.txt
myfiles/Con/manifesto/man2.txt
myfiles/Lab/speeches/speech1.txt
myfiles/Lab/speeches/speech2.txt
myfiles/Lab/manifesto/man1.txt
myfiles/Lab/manifesto/man2.txt
```

with the desired behaviour being:
```r
> head(mydata)
                                texts    party          type
Con_speeches_speech1.txt    "Blah..."    "Con"      "speech"
Con_speeches_speech2.txt    "Blah bl"    "Con"      "speech"
Con_manifesto_speech1.txt   "Blah!.."    "Con"   "manifesto"
Con_manifesto_speech2.txt     "Blah?"    "Con"   "manifesto"
Lab_speeches_speech1.txt    "Blah..."    "Lab"      "speech"
Lab_speeches_speech2.txt    "Blah bl"    "Lab"      "speech"
Lab_manifesto_speech1.txt   "Blah!.."    "Lab"   "manifesto"
Lab_manifesto_speech2.txt     "Blah?"    "Lab"   "manifesto"
```

**Comment by adamobeng** [comment]
That'll get hairy if you want to combine filename and directory docvars. What order would you specify the names in?

**Comment by pnulty** [comment]
@kbenoit  That suggested behaviour looks good to me.

@adamobeng The way it worked on the last version of this that I remember working on was that there was an optional argument "docvarsfrom", which would be either "filenames" or "dirnames" or other things that we supported. You couldn't combine them.

**Comment by kbenoit** [comment]
I think this one is really easy to solve now, by parsing the docname:
```r
> (tmp <- readtext('tests/data/glob/subdir*'))
                 text
subdir1/test.txt     
subdir2/test.txt  
> do.call(rbind, strsplit(docnames(tmp), "/"))[, -max(length(tmp)), drop = FALSE]
     [,1]      
[1,] "test.txt"
[2,] "test.txt"
```
and those can be appended to the return object, and given a docvarname supplied by the user through `docvarnames = `.

**Comment by adamobeng** [comment]
We only need to change one line in the code, to get docvars from the full path rather than just the filename:

```r
> docvars(readtext('../data/docvars/one/*', docvarsfrom='filenames', dvsep='_'))
             docvar1 docvar2
1_apple.txt        1   apple
2_orange.txt       2  orange
> docvars(readtext('../data/docvars/one/*', docvarsfrom='filenames', dvsep='[/_]'))
             docvar1 docvar2
1_apple.txt        1   apple
2_orange.txt       2  orange
> docvars(readtext('../data/docvars/one/*', docvarsfrom='filepaths', dvsep='[/_]',))
             docvar1 docvar2 docvar3 docvar4 docvar5    docvar6
1_apple.txt       ..    data docvars     one       1  apple.txt
2_orange.txt      ..    data docvars     one       2 orange.txt
```

**Comment by kbenoit** [comment]
didn't work for this:
```
> readtext('tests/data/glob/subdir*', docvarsfrom='filenames', dvsep='[/_]')
                 text docvar1
subdir1/test.txt         test
subdir2/test.txt         test
```

**Comment by adamobeng** [comment]
I haven't changed the line of code yet (note "filenames" vs "filepaths")

**Comment by adamobeng** [comment]
@kbenoit, see https://github.com/kbenoit/readtext/tree/feature/filepaths

**Comment by kbenoit** [comment]
Nice. Let's include a note that the `dvsep` is a regular expression, and perhaps provide an example using the character class of `[/_]` as in your example above.
