### ISSUE TITLE
Failure installing read text

### ISSUE THREAD

**Issue by dkholo** [kbenoit/readtext#109]
I am getting the following error when I try to install read text package.
My code worked fine earlier and now R studio no longer able to see readtext package so I had to re-install.
I am getting the following error:
> library(readtext)
Error in library(readtext) : there is no package called ‘readtext’
> devtools::install_github("kbenoit/readtext")
Downloading GitHub repo kbenoit/readtext@master
from URL https://api.github.com/repos/kbenoit/readtext/zipball/master
Installing readtext
"C:/PROGRA~1/MICROS~1/RCLIEN~1/R_SERVER/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/dkholo/AppData/Local/Temp/RtmpKMdC0y/devtoolsc2c43d73351/kbenoit-readtext-4350e5c"  \
  --library="C:/Users/dkholo/Documents/R/win-library/3.3" --install-tests 

ERROR: dependency 'antiword' is not available for package 'readtext'
* removing 'C:/Users/dkholo/Documents/R/win-library/3.3/readtext'
Error: Command failed (1)

I would appreciate some assistance with this issue.

**Comment by dkholo** [comment]
This seems to be R studio 64 bit specific issue.
I was able to install readtext when I switched to 32 bit version.

**Comment by kbenoit** [comment]
We would need the results of `sessionInfo()` even to begin to diagnose this issue.

**Comment by kbenoit** [comment]
See https://github.com/kbenoit/readtext/issues/110.
