### ISSUE TITLE
Support XPath as textfield argument

### ISSUE THREAD

**Issue by adamobeng** [kbenoit/readtext#13]
See https://github.com/kbenoit/quanteda/issues/245

cc @cownr10r

**Comment by adamobeng** [comment]
At the moment `textfield` can be an integer, in which case it's a field number, or a character, in which case it's a field name. To also support characters which are XPath expressions, we could either try to autodetect if an given textfield is an XPath or add another argument which specifies the type of textfield explicitly.

I think the second approach makes more sense, and would be extensible to other types of textfield in the future. What do you think @ken, @pnulty ?

**Comment by kbenoit** [comment]
I'm not sure what an XPath expression is...

**Comment by adamobeng** [comment]
If your XML document was

```
<A>
  <B>
    <C/>
  </B>
  <B>
    <C/>
  </B>
</A>
```

You could specify `textfield='/A/B'` to include the content of the `B` tags as your documents. You could use that to extract paragraphs vs. pages or something similar.

**Comment by adamobeng** [comment]
@cownr10r, support for this exists in the branch feature/XPath and will be integrated into quanteda in due course (at least by v1.0.0). You can experiment with something like

```{r}
devtools::install_github('kbenoit/readtext', ref='feature/XPath')
library(readtext)

readtxt('Sample 1.xml',
                      textfield='/tei:TEI/tei:text/tei:body//tei:p',
                      namespaces=c(tei = "http://www.tei-c.org/ns/1.0"))

```
