### ISSUE TITLE
Add support for pdf conversion and import

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/readtext#16]
This would be a wrapper to xpdf (and pdftotext), which would require separate installation. Options to be passed through in a "rationalized" manner.

**Comment by adamobeng** [comment]
(PR)[https://github.com/kbenoit/readtext/pull/22] uses `pdftools::pdf_text`

**Comment by kbenoit** [comment]
Fixed in https://github.com/kbenoit/readtext/commit/0ab715ef2d0b0410a7536fde5baa4403f16d8c72.
