### ISSUE TITLE
Add support for MS word conversion and import

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/readtext#17]
This would be a wrapper to antiword, for .doc and .docx files, which would require separate installation. Options to be passed through in a "rationalized" manner.

**Comment by adamobeng** [comment]
Implementation [in the PR](https://github.com/kbenoit/readtext/pull/22) uses antiword via `tm::readDOC` for .doc files and `qdapTools::read_docx` for .docx files.

**Comment by kbenoit** [comment]
Fixed in https://github.com/kbenoit/readtext/commit/0ab715ef2d0b0410a7536fde5baa4403f16d8c72.
