### ISSUE TITLE
Make name of package and function consistent

### ISSUE THREAD

**Issue by adamobeng** [kbenoit/readtext#2]
Should either both be **readtxt** or **readtext**

**Comment by kbenoit** [comment]
I thought about that, but with the roxygen `"_PACKAGE"` (see `readtext-package.R`) for the package documentation, it automatically creates an alias to `readtext-package` when you search `?readtext`. I found this pretty annoying so renamed the function. But I agree with you so the better solution is probably a workaround.

**Comment by kbenoit** [comment]
We can resolve this default behaviour by changing the package roxygen def to:

```r
#' Import and handling for plain and formatted text files
#'
#' Description here...
#' @docType package
#' @name readtext-package
#' @author Ken Benoit, Paul Nulty, and Adam Obeng
NULL
```

Then:

```r
> library(readtext)
> ?readtext
No documentation for ‘readtext’ in specified packages and libraries:
you could try ‘??readtext’
> ?readtxt  # works
> ?`readtext-package`  # loads the package help page
> help(package = "readtext")  # loads the package index

```

**Comment by adamobeng** [comment]
If I do that, then trying to build the documentation raises ` Missing name at readtext-package.R:17`.
