### ISSUE TITLE
Add options to normalise or remove character classes

### ISSUE THREAD

**Issue by adamobeng** [kbenoit/readtext#24]
This should by specifying Unicode character properties, and could replace, e.g. all quotation marks by U+0022 QUOTATION MARK, all line separators by U+2028 LINE SEPARATOR, or remove private use area characters altogether.

Also, remove the existing normalisation of hyphens and 'smart' quotes.

Moved from https://github.com/kbenoit/quanteda/issues/190

**Comment by adamobeng** [comment]
@kbenoit Do we want to allow the user to choose which classes to replace? If not, I'm ready to make  a PR from https://github.com/kbenoit/readtext/tree/feature/character_class_replacement

**Comment by kbenoit** [comment]
Initially I'd say no, no choice. Can be a future feature.

**Comment by adamobeng** [comment]
PR initiated: https://github.com/kbenoit/readtext/pull/50.
