### ISSUE TITLE
Tests for utils.R

### ISSUE THREAD

**Issue by adamobeng** [kbenoit/readtext#27]

**Comment by kbenoit** [comment]
What's the bug - just the fact that we do not have any tests yet for utils.R functions?

**Comment by adamobeng** [comment]
I think they hadn't been copied over from quanteda, but they're mostly there now. There are still a few things missing: https://codecov.io/gh/kbenoit/readtext/src/5d10859e78708c95835e69e0471a3f5fee3029b7/R/utils.R
