### ISSUE TITLE
Search for and deal with nonbreaking spaces

### ISSUE THREAD

**Issue by adamobeng** [kbenoit/readtext#30]
I figured out why there are sometimes non-breaking spaces in my code: I have a British Mac keyboard on which the octothorpe is accessed with `⌥ Opt`+`3`, but `⌥ Opt`+`Space` creates a non-breaking space. So if you go to type a comment starting with an octothorpe but you start holding down `⌥ Opt` before you press space, then you get a non-breaking space before your comment...

**Comment by kbenoit** [comment]
So now you see them too! They don't cause an error, but they are odd-looking. 

Afte 25 years with Emacs, I have switched to https://atom.io. It's awesome and gets better all the time. With live preview for markdown, among many other things. (Although I live with RStudio's editor to get all the other benefits - the 1.0 of RStudio adds some outstanding features to an already great IDE.

**Comment by adamobeng** [comment]
It's nothing to do with vim; I tried atom.io and it does the same thing.

I'm using [this](https://gist.github.com/adamobeng/9cce7345cb826d3ddab77620a900f3b3) as a pre-commit hook now, so hopefully that will fix it.

**Comment by kbenoit** [comment]
The new MacBook Pros eliminate the physical Esc key - not good news for Vim/Emacs users...
