### ISSUE TITLE
Replace read.csv with fread

### ISSUE THREAD

**Issue by adamobeng** [kbenoit/readtext#4]

**Comment by adamobeng** [comment]
`data.table::fread` only supports encodings 'Latin-1', 'utf-8' and 'unknown'. @kbenoit , would it be acceptable to first read in the file using `file` with the specified encoding, then call `fread` on that?

**Comment by kbenoit** [comment]
Sounds like that's just the `Encoding` bit. As long as `data.table::fread` does not do any translation, then that strategy would work fine. In fact we could read it in and then run `readtext::encoding` on the object's `texts` field, to help determine what encoding it was.

**Comment by adamobeng** [comment]
@adamobeng investigate http://readr.tidyverse.org/

**Comment by adamobeng** [comment]
Unlike `data.table::fread`, `readr::readr` will not guess delimiters etc. It also uses `stri_enc_detect` to guess encodings, so it won't work for our purposes.
