### ISSUE TITLE
reading in and joining multiple structures files

### ISSUE THREAD

**Issue by pnulty** [kbenoit/readtext#59]
Here is a problem I am considering with readtext and quanteda. The second part might be a usage question rather than a bug for quanteda, but I think the readtext part is an issue.

I have multiple txt files that constitute a single corpus, and each txt contains one document per line. If I use readtext in the default way, each of these files is treated as a single document (I tried this with 'textfield = 1' but got the same result). However, if I rename the extension to tsv, I can correctly read them in one file at a time like this: 

```
fs <- list.files('~/Dropbox/data/corpora/FT_processed/', full.names = TRUE)
tmp <- sapply(fs, function(x) corpus(readtext(x), textField=1) )
```

I now need to join this list of corpus sources into a single corpus. I tried this:

`t2 <- do.call('+',tmp)`

But it gives an error. Below I've pasted a reproducible example of this error using a built-in corpus. I'm happy to have a go at coding a solution for the readtext part, one easy fix would be an extra flag to read txt files one line at a time. For the corpus joining problem, apologies if I"m behind the curve here, is there another solution for joining a list of corpora, or am I doing the 'do.call' incorrectly?

```
g <- corpus_subset(ie2010Corpus, party == 'Green')
l <- corpus_subset(ie2010Corpus, party == 'LAB')
f <- corpus_subset(ie2010Corpus, party == 'FF')
tmp <- g+f+l #this works
tmp <- do.call('+',c(g,f,l))  # Error in `+`  ...
```

I see in the docs that the `c()` operator is also available, but while this works if I have a number of individual variable names that I want to join into a single corpus, it doesn't help if I have a list of corpus objects that I want to join together. I also tried using lapply instead of sapply in the original corpus/readtext anonymous function, but I still just get a list of corpora.

**Comment by kbenoit** [comment]
How about putting a set of the `FT_processed` files into the QUANTESS directory so I can test on them directly?

In your example, `+` will not work because the `c.corpus()` has already combined them in the second argument. But more generally, `+` cannot take more than two arguments, e.g.
```r
> do.call('+', list(1, 2, 3))
Error in `+`(1, 2, 3) : operator needs one or two arguments
```

**Comment by pnulty** [comment]
I've done that now. The code I have is:

```
library(quanteda)
library(readtext)
fs <- list.files('~/Dropbox/QUANTESS/paul_ft_sample/', full.names = TRUE)
corpus_list <- lapply(fs, function(x) corpus(readtext(x), textField=1) )
```
And I'd like to make the corpus list into a single corpus.

**Comment by kbenoit** [comment]
ooooh, but we gots wildcards:

```r
require(readtext)

ftcorpus <- corpus(readtext("~/Dropbox/QUANTESS/paul_ft_sample/*.tsv", verbosity = 0))
summary(ftcorpus, 5)
# Corpus consisting of 4574 documents, showing 5 documents.
# 
#       Text Types Tokens Sentences
# 9104.tsv.1   372   1145        21
# 9104.tsv.2   345    882        35
# 9104.tsv.3   494   1463        32
# 9104.tsv.4   237    490        18
# 9104.tsv.5   373    778        27
# 
# Source:  /Users/kbenoit/Dropbox (Personal)/GitHub/sophistication/R_package/* on x86_64 by kbenoit
# Created: Tue Feb 28 21:26:42 2017
# Notes:   
```

Need to fix that verbosity thing though.

**Comment by pnulty** [comment]
Ah, thanks, I had only tried the wildcard with the txt files. I'll close.
