### ISSUE TITLE
Remove the camelCase from function arguments

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/readtext#66]
And anywhere else it occurs.

**Comment by stefan-mueller** [comment]
I will take care of this, and make pull requests.

**Comment by kbenoit** [comment]
this is very tricky since we will need to deprecate the old arguments rather than remove them, so might not be something to take on at this stage unless you are confident you can make the old ones work, but quietly (and possibly with a note).

**Comment by kbenoit** [comment]
might be worth reading: https://ropensci.org/blog/technotes/2017/01/05/package-evolution

**Comment by stefan-mueller** [comment]
Ok, I thought it's easier. Thanks for the link. Maybe I focus on the **readtext** vignette instead ([#62](https://github.com/kbenoit/readtext/issues/62)). I should be able to have a draft by the end of May/early June if that's ok.

**Comment by kbenoit** [comment]
Actually I thought this was for **quanteda** ... for **readtext** this is much simpler, so if you want to change the camelCase, that's fine.

**Comment by stefan-mueller** [comment]
Yes, it's only the camelCase change in **readtext**. I will simply check all files and replace `camelCase`-like functions/words with `snake_case` following this [style guide](http://r-pkgs.had.co.nz/style.html).

**Comment by kbenoit** [comment]
It's ok, I have just fixed these. There are only three:

* `ignoreMissingFiles` in `readtext()`
* `encodedTextFiles` - should become `data_files_encodedtext` according to the new naming conventions from **quanteda**
* `encodedTexts` should be `data_char_encodedtexts`
