### ISSUE TITLE
Add option to remove page numbers

### ISSUE THREAD

**Issue by stefan-mueller** [kbenoit/readtext#72]
Since **readtext** also imports PDF (thanks for this!), it might be good to add an option `remove_page_numbers=TRUE/FALSE`, basically a regular expression that removes page numbers which are imported from the top or bottom of each page. I tried several regular expressions today, and this one should work.

```r
gsub("\n\\d*\n", "", x)
```
Especially for beginners this option might be good because it does not affect numbers in the text, but only removes page numbers that occur in a separate row.

If you think this is a good idea and belongs to **readtext** (rather than `corpus` in **quanteda**), I can change the code and make a pull request.

**Comment by kbenoit** [comment]
Thanks @stefan-mueller. In my experience the page numbers come in different formats, e.g. "p1", "p.1", "-1-", etc. so trying to catch them all is likely to be quite hard. 

Also two things on your expression:
1. Shouldn't that be "\\n" not "\n", and
2. We're moving to all **stringi** handling, so it would be better as `stringi::stri_replace_all_regex"...

**Comment by stefan-mueller** [comment]
Ok, I get it, it's probably to difficult to find a generalised solution. What about updating README.md and adding a small subsection on regular expressions to remove page numbers? I could come up with some examples, the necessary regular expressions, and also provide a link to the [Regular Expression Cheatsheet](http://web.mit.edu/hackl/www/lab/turkshop/slides/regex-cheatsheet.pdf).

**Comment by kbenoit** [comment]
Would make a great part of a vignette!

**Comment by stefan-mueller** [comment]
Ok, good idea. Let's keep this in mind when dealing with issue [#62](https://github.com/kbenoit/readtext/issues/62). I am happy to help creating a vignette for **readtext**.

**Comment by kbenoit** [comment]
That would be fantastic!

**Comment by stefan-mueller** [comment]
See section 4.1 of **readtext** [vignette](https://github.com/kbenoit/readtext/blob/master/inst/doc/readtext_vignette.Rmd).
