### ISSUE TITLE
Could not find package root

### ISSUE THREAD

**Issue by wfio** [kbenoit/readtext#73]
Hola, I'm behind a firewall so I can't use devtools to install the package. As a result, I downloaded the master zip file. I've tried devtools::install::local on the zip and it won't work. Returns the error: Error: Could not find package root.

So, I tried extracting the the contents of the Zip and WinZip says the file is corrupt. So, I used Explorer to copy and paste the contents out. Then I tried devtools install again on that and received the same package root error.

I have no issues installing via github on my linux box (surprised). But this Windows machine appears to hate you.

**Comment by kbenoit** [comment]
It will be on CRAN very soon...  In the meantime, try

1. Download the zip file from GitHub. On my system this downloaded to `~/Downloads/readtext-master.zip`.

2. From your Finder/File Explorer/etc click to extract the contents of that file. On my system, this created a folder with the contents called `~/Downloads/readtext-master/`.

3. Install it this way (assumes you have RTools installed if you are using Windows, or Xcode if you are using macOS)
    ```r
    devtools::install("~/Downloads/readtext-master/", type = "source")
    ```
