### ISSUE TITLE
Automatically install non-R dependencies

### ISSUE THREAD

**Issue by adamobeng** [kbenoit/readtext#76]
This would make it easier for windows user to install, e.g. antiword. pdftools does this with poppler.

CC @trinker

**Comment by trinker** [comment]
@jeroen had suggested creating an R package that wraps antiword

Antiword: http://www.winfield.demon.nl/
Usage Blog Article: https://www.maketecheasier.com/antiword-read-word-documents-in-terminal/

Jeroen not sure of official flags.  The website doesn't seem to have them nor did the README.  They have to be documented somewhere but I am overlooking them.

**Comment by jeroen** [comment]
The antiword pkg is on cran now.
