### ISSUE TITLE
Support passing in a directory

### ISSUE THREAD

**Issue by lmullen** [kbenoit/readtext#82]
In addition to the many formats that readtext already supports, the `readtext()` function could support passing in a single path to a directory. If `file.info(path)$dir` returns `TRUE`, then `readtext()` could get all the paths from that directory and proceed with the logic that is already in place.

**Comment by kbenoit** [comment]
I think we do that already, with e.g. `readtext("myfilesdir/*")`.  We can even wildcard parts of paths, such as `readtext("myfilesdir/speech*/*.txt")` will pick up `myfilesdir/speech_1991/*`, `myfilesdir/speech_1992/*`, etc but not `myfilesdir/programme_1991/*`.

But we will verify!

**Comment by lmullen** [comment]
Ah. I didn't realize you did file globbing in that way, which does work for me. I do think it makes sense for this kind of swiss-army knife package to support passing in a dir without globs, but I can also see why would wouldn't want to support yet another complication.

**Comment by kbenoit** [comment]
Already works:
```r
readtext(paste0(system.file("extdata/", package = "readtext"), "txt/UDHR/"))
## readtext object consisting of 13 documents and 0 docvars.
## # data.frame [13 × 2]
##              doc_id                      text
## *             <chr>                     <chr>
## 1  UDHR_chinese.txt "世界人权宣言\n联合国"...
## 2    UDHR_czech.txt           "VŠEOBECNÁ "...
## 3   UDHR_danish.txt           "Den 10. de"...
## 4  UDHR_english.txt           "Universal "...
## 5   UDHR_french.txt           "Déclaratio"...
## 6 UDHR_georgian.txt           "FLFVBFYBC "...
## # ... with 7 more rows
```
(note the new print method - although it remains a data.frame)
