### ISSUE TITLE
Change "textfield" to "text_field"

### ISSUE THREAD

**Issue by stefan-mueller** [kbenoit/readtext#83]
For reasons of consistency with **quanteda**, I think we should change `textfield` to `text_field` which is used in `corpus` objects. If you agree, I change all occurrences of `textfield` and make a PR.

**Comment by kbenoit** [comment]
Thanks but following this weekend's workshop we are considering making changes along this line but in a way that meets the emerging standard on inter-operability between corpus-like objects. Once I have time this weekend I'll sort it out. So no need.
